# Generated by Django 4.1 on 2022-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
